### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [ActiveVisionLab/gaussctrl#10]
Hi!I meet a problem.
Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 76, in setup
    self.pipeline.render_reverse()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_pipeline.py", line 126, in render_reverse
    rendered_image = self._model.get_outputs_for_camera(current_cam)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_model.py", line 219, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_model.py", line 174, in get_outputs
    rgb, alpha = rasterize_gaussians(  # type: ignore
TypeError: rasterize_gaussians() got an unexpected keyword argument 'return_alpha'

Is this parameter ‘return_alpha’ required?
Because when I removed this parameter, a new error appeared:
Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_trainer.py", line 76, in setup
    self.pipeline.render_reverse()
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_pipeline.py", line 126, in render_reverse
    rendered_image = self._model.get_outputs_for_camera(current_cam)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/gaussctrl/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_model.py", line 218, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
  File "/mnt/cloud_disk/yyhyyh/gaussctrl/gaussctrl/gc_model.py", line 174, in get_outputs
    rgb, alpha = rasterize_gaussians(  # type: ignore
ValueError: too many values to unpack (expected 2)

Do you know how to solve it?

**Comment by Brooke-byte** [comment]
使用gsplat==0.1.3而不是==0.1.2.1解决了这个问题

**Comment by WarrenZZZZL** [comment]
> 使用gsplat==0.1.3而不是==0.1.2.1解决了这个问题

很有效感恩！
