### ISSUE TITLE
RuntimeError: expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by WarrenZZZZL** [ActiveVisionLab/gaussctrl#20]

**Comment by SydneyWarrenZhao** [comment]
Hi, do you know how to debug this?

**Comment by ScienceLi1125** [comment]
Hi, I have met the same error. Have you solved that? Thanks a lot!

**Comment by ZhaoLongjiea** [comment]
> Hi, I have met the same error. Have you solved that? Thanks a lot!

No, I haven't. Still working on this. I just thought I had solved this.

**Comment by ZhaoLongjiea** [comment]
> Hi, I have met the same error. Have you solved that? Thanks a lot!

Can you put your full codes of the bug?

**Comment by ScienceLi1125** [comment]
```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/gaussctrl/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/hdd1/user/workspace/gaussctrl/gaussctrl/gc_trainer.py", line 76, in setup
    self.pipeline.render_reverse()
  File "/hdd1/user/workspace/gaussctrl/gaussctrl/gc_pipeline.py", line 131, in render_reverse
    rendered_image = self._model.get_outputs_for_camera(current_cam)
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/hdd1/user/workspace/gaussctrl/gaussctrl/gc_model.py", line 219, in get_outputs_for_camera
    outs = self.get_outputs(camera.to(self.device))
  File "/hdd1/user/workspace/gaussctrl/gaussctrl/gc_model.py", line 140, in get_outputs
    self.xys, depths, self.radii, conics, num_tiles_hit, cov3d = project_gaussians(  # type: ignore
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/gsplat/project_gaussians.py", line 59, in project_gaussians
    return _ProjectGaussians.apply(
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/gsplat/project_gaussians.py", line 107, in forward
    ) = _C.project_gaussians_forward(
  File "/home/user/anaconda3/envs/gaussctrl/lib/python3.10/site-packages/gsplat/cuda/__init__.py", line 9, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: expected scalar type Float but found BFloat16
```

**Comment by michael861227** [comment]
Hi, I have met the same error. 
Did anyone solve the problem?
Thanks a lot!

**Comment by HuangZhongTian1009** [comment]
Did anyone solve the problem?

**Comment by jingwu2121** [comment]
Hi, please try manually setting the types of the related variables, it may help resolve the issue. It’s also possible that this is caused by the environment setup.

In case this is environment-related, I’ve updated the environment configuration to better support the repository. Please check [this section](https://github.com/ActiveVisionLab/gaussctrl#2%EF%B8%8F%E2%83%A3-use-docker-image), where I’ve added Docker support. Using the Docker environment may be easier, as it comes with all the required packages pre-installed.
