### ISSUE TITLE
No module named 'lang_sam'

### ISSUE THREAD

**Issue by WarrenZZZZL** [ActiveVisionLab/gaussctrl#27]
(gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl$ git clone https://github.com/luca-medeiros/lang-segment-anything && cd lang-segment-anything
Cloning into 'lang-segment-anything'...
remote: Enumerating objects: 376, done.
remote: Counting objects: 100% (160/160), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 376 (delta 115), reused 91 (delta 91), pack-reused 216 (from 1)
Receiving objects: 100% (376/376), 27.68 MiB | 19.23 MiB/s, done.
Resolving deltas: 100% (170/170), done.
(gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl/lang-segment-anything$ pip install -e .
Obtaining file:///home/lzha0538/3Dediting/gaussctrl/lang-segment-anything
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting sam-2@ git+https://github.com/facebookresearch/segment-anything-2@c2ec8e14a185632b0a5d8b161928ceb50197eddc (from lang-sam==0.2.1)
  Cloning https://github.com/facebookresearch/segment-anything-2 (to revision c2ec8e14a185632b0a5d8b161928ceb50197eddc) to /tmp/pip-install-2s0nqgje/sam-2_3e1707f71d1849cb840b8f3fe93febe2
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/segment-anything-2 /tmp/pip-install-2s0nqgje/sam-2_3e1707f71d1849cb840b8f3fe93febe2
  Running command git rev-parse -q --verify 'sha^c2ec8e14a185632b0a5d8b161928ceb50197eddc'
  Running command git fetch -q https://github.com/facebookresearch/segment-anything-2 c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Running command git checkout -q c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Resolved https://github.com/facebookresearch/segment-anything-2 to commit c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: gradio==3.38.0 in /home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages (from lang-sam==0.2.1) (3.38.0)
Collecting litserve==0.2.3 (from lang-sam==0.2.1)
  Using cached litserve-0.2.3-py3-none-any.whl.metadata (16 kB)
Collecting opencv-python-headless==4.10.0.84 (from lang-sam==0.2.1)
  Using cached opencv_python_headless-4.10.0.84-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pydantic==2.9.2 (from lang-sam==0.2.1)
  Using cached pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting transformers==4.44.2 (from lang-sam==0.2.1)
  Using cached transformers-4.44.2-py3-none-any.whl.metadata (43 kB)
Collecting uvloop==0.20.0 (from lang-sam==0.2.1)
  Using cached uvloop-0.20.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: torch==2.4.1 in /home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages (from lang-sam==0.2.1) (2.4.1)
Requirement already satisfied: torchvision==0.19.1 in /home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages (from lang-sam==0.2.1) (0.19.1)
INFO: pip is looking at multiple versions of lang-sam to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'lang-sam' requires a different Python: 3.8.20 not in '>=3.11'
(gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl/lang-segment-anything$ ns-train splatfacto --output-dir unedited_models --experiment-name bear --viewer.quit-on-train-completion True nerfstudio-data --data data/bear
/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/field_components/activations.py:32: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)
/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/field_components/activations.py:39: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, g):
Traceback (most recent call last):
  File "/home/lzha0538/miniconda3/envs/gaussctrl/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/configs/method_configs.py", line 669, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 189, in load
    module = import_module(match.group('module'))
  File "/home/lzha0538/miniconda3/envs/gaussctrl/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_config.py", line 30, in <module>
    from gaussctrl.gc_pipeline import GaussCtrlPipelineConfig
  File "/home/lzha0538/3Dediting/gaussctrl/gaussctrl/gc_pipeline.py", line 26, in <module>
    from lang_sam import LangSAM
ModuleNotFoundError: No module named 'lang_sam'
(gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl/lang-segment-anything$

**Comment by WarrenZZZZL** [comment]
gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl/lang-segment-anything$ 
pip install -U git+https://github.com/luca-medeiros/lang-segment-anything.git
Collecting git+https://github.com/luca-medeiros/lang-segment-anything.git
  Cloning https://github.com/luca-medeiros/lang-segment-anything.git to /tmp/pip-req-build-6nrxv528
  Running command git clone --filter=blob:none --quiet https://github.com/luca-medeiros/lang-segment-anything.git /tmp/pip-req-build-6nrxv528
  Resolved https://github.com/luca-medeiros/lang-segment-anything.git to commit 19cb3670caea21e11b35e01ce1115a4a35b27fb5
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting sam-2@ git+https://github.com/facebookresearch/segment-anything-2@c2ec8e14a185632b0a5d8b161928ceb50197eddc (from lang-sam==0.2.1)
  Cloning https://github.com/facebookresearch/segment-anything-2 (to revision c2ec8e14a185632b0a5d8b161928ceb50197eddc) to /tmp/pip-install-ghaj05zj/sam-2_8378e96afc7c428d8393693c02d96b5d
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/segment-anything-2 /tmp/pip-install-ghaj05zj/sam-2_8378e96afc7c428d8393693c02d96b5d
  Running command git rev-parse -q --verify 'sha^c2ec8e14a185632b0a5d8b161928ceb50197eddc'
  Running command git fetch -q https://github.com/facebookresearch/segment-anything-2 c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Running command git checkout -q c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Resolved https://github.com/facebookresearch/segment-anything-2 to commit c2ec8e14a185632b0a5d8b161928ceb50197eddc
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of lang-sam to determine which version is compatible with other requirements. This could take a while.
ERROR: Ignored the following yanked versions: 2.8.0, 3.0.7, 3.1.2, 3.13.1, 3.45.0b9, 3.45.0b10, 3.45.0b11, 3.45.0b12, 3.45.0b13, 4.0.0b15, 4.7.0
ERROR: Ignored the following versions that require a different python version: 5.0.0 Requires-Python >=3.10; 5.0.0b1 Requires-Python >=3.10; 5.0.0b10 Requires-Python >=3.10; 5.0.0b5 Requires-Python >=3.10; 5.0.0b6 Requires-Python >=3.10; 5.0.0b7 Requires-Python >=3.10; 5.0.0b8 Requires-Python >=3.10; 5.0.0b9 Requires-Python >=3.10; 5.0.1 Requires-Python >=3.10; 5.0.2 Requires-Python >=3.10; 5.1.0 Requires-Python >=3.10; 5.3.0 Requires-Python >=3.10; 5.4.0 Requires-Python >=3.10; 5.5.0 Requires-Python >=3.10; 5.6.0 Requires-Python >=3.10; 5.7.0 Requires-Python >=3.10; 5.7.1 Requires-Python >=3.10; 5.8.0 Requires-Python >=3.10; 5.9.0 Requires-Python >=3.10; 5.9.1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement gradio==5.0.2 (from lang-sam) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.4.0, 0.4.1, 0.4.2, 0.4.4, 0.5.0, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9.2, 0.9.9.3, 0.9.9.5, 0.9.9.6, 0.9.9.7, 0.9.9.8, 0.9.9.9, 0.9.9.9.2, 1.0.0a1, 1.0.0a3, 1.0.0a4, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.8, 1.1.8.1, 1.1.9, 1.2.2, 1.2.3, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 4.0, 4.44.1)
ERROR: No matching distribution found for gradio==5.0.2
(gaussctrl) (base) lzha0538@gpu1-3w-1:~/3Dediting/gaussctrl/lang-segment-anything$

**Comment by WarrenZZZZL** [comment]
always compatibility issues，cryyyyyyy

**Comment by WarrenZZZZL** [comment]
could you please review the installation process? Thank your great work.

**Comment by jingwu2121** [comment]
Hi, it seems that Lang-SAM is updated and requires Python > 3.11 now, can you please try using Python 3.11 and install nerfstudio using the same procedure, and install Lang-SAM

**Comment by WarrenZ3** [comment]
> Hi, it seems that Lang-SAM is updated and requires Python > 3.11 now, can you please try using Python 3.11 and install nerfstudio using the same procedure, and install Lang-SAM

Yes, I have tried using python 3.11, but python 3.11 is incompatible with other packages. Ihave tried many times. It seems like I've fallen into a loop of bugs caused by many incompatible packages, like a nesting doll.

**Comment by jingwu2121** [comment]
Hi, can you switch to this branch, and install lang-sam locally by doing `pip install -e .`, this should work
https://github.com/luca-medeiros/lang-segment-anything/tree/fix-no_detection

**Comment by WarrenZZZZL** [comment]
> Hi, can you switch to this branch, and install lang-sam locally by doing `pip install -e .`, this should work https://github.com/luca-medeiros/lang-segment-anything/tree/fix-no_detection

Thank you very much! It works! God bless you. I have got the result of your model.
